name: Deploy Resume to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 8
        run_install: false
        
    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
        
    - name: Setup pnpm cache
      uses: actions/cache@v4
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
        
    - name: Install dependencies
      run: |
        if [ -f pnpm-lock.yaml ]; then
          pnpm install --frozen-lockfile || pnpm install --no-frozen-lockfile
        else
          pnpm install
        fi
      
    - name: Build resume
      run: pnpm serve
      
    # - name: Install Chrome for Puppeteer
    #   run: |
    #     npx puppeteer browsers install chrome
    #     echo "PUPPETEER_EXECUTABLE_PATH=$(npx puppeteer browsers install chrome | grep -o '/[^[:space:]]*chrome')" >> $GITHUB_ENV
      
    # - name: Setup virtual display
    #   run: |
    #     sudo apt-get update
    #     sudo apt-get install -y xvfb
    #     export DISPLAY=:99
    #     Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      
    # - name: Generate PDF
    #   run: pnpm pdf
    #   env:
    #     DISPLAY: :99
    #     PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
    #     PUPPETEER_ARGS: "--no-sandbox --disable-setuid-sandbox --disable-dev-shm-usage --disable-accelerated-2d-canvas --no-first-run --no-zygote --single-process --disable-gpu --headless=new"
      
    - name: Rename resume file
      run: cp index.html resume.html
      
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: '.'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
